services:
  backend:
    build:
      context: ../../services/backend
      dockerfile: Dockerfile.dev
    image: osyle/backend:latest
    container_name: osyle-backend
    volumes:
      - ../../services/backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ../../services/backend/.env
    shm_size: "2gb" # Required for Chromium

  frontend:
    build:
      context: ../../services/frontend
      dockerfile: Dockerfile.dev
    image: osyle/frontend:latest
    container_name: osyle-frontend
    volumes:
      - ../../services/frontend/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - backend
