services:
  backend:
    build:
      context: ../../services/backend
      dockerfile: Dockerfile.prod
    image: osyle/backend:latest
    container_name: osyle-backend
    ports:
      - "8000:8000"
    env_file:
      - ../../services/backend/.env
    shm_size: "2gb" # Required for Chromium

  frontend:
    build:
      context: ../../services/frontend
      dockerfile: Dockerfile.prod
    image: osyle/frontend:latest
    container_name: osyle-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
